### ISSUE TITLE
Basic model of hierarchy / predicability

### ISSUE THREAD

**Issue by mhtess** [mhtess/comparison-class#1] opened 2016-07-07 18:32 UTC

**Comment by lopez-brau** [comment] 2016-07-10 00:52
False alarm on that last commit. The mixture function added them all together but as if they were all children of the same parent node (as opposed to a cascading manner, until it reached the desired node). I'm almost done modifying it to work as intended.

**Comment by lopez-brau** [comment] 2016-07-10 05:31
I believe the tree part is almost complete. One thing that I noted is that the priors that are further up the tree have a higher impact on the final prior distribution. This could be fixed by fiddling with the priorWeights function.

**Comment by mhtess** [comment] 2016-07-10 07:39
This is looking solid. Good point about the relative influence of different parts of the hierarchy. I'm wondering: is it even coherent to mix priors of lower than one level? We may just one to mix priors of one level lower on the tree.

**Comment by lopez-brau** [comment] 2016-07-11 06:28
I would think so. If we take the example of the category "solid objects," which is above the category "animals," the kinds "animals" and "plants" (two tiers down) would make some sort of impact. Perhaps I could halve the contribution of the priors for each tier they have to ascend?

**Closed as completed** 2016-07-11 23:09 UTC
